<a href="https://colab.research.google.com/github/madrigaljose/ML-foundations/blob/master/Dense_Network_Experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import keras
import tensorflow
import pandas as pd
import numpy as np

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

In [19]:
from seaborn import load_dataset
iris_df = load_dataset("iris")
iris_df.species = pd.Categorical(iris_df.species, categories=['setosa','versicolor','virginica'])
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
iris_df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [21]:
iris_df.species.value_counts()

virginica     50
versicolor    50
setosa        50
Name: species, dtype: int64

In [22]:
iris_df.species.cat.codes.value_counts()

2    50
1    50
0    50
dtype: int64

In [23]:
X = iris_df.drop('species', axis=1)
X.head(2)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [24]:
X=X.values
X.shape

(150, 4)

In [25]:
y = iris_df.species.cat.codes
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int8

In [26]:
y.tail()

145    2
146    2
147    2
148    2
149    2
dtype: int8

In [27]:
y=y.values
y.shape

(150,)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=0, stratify=y)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((112, 4), (38, 4), (112,), (38,))

In [29]:
y_train[0]

1

In [31]:
from tensorflow.keras.utils import to_categorical
n_classes = 3
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

In [32]:
y_train.shape, y_valid.shape

((112, 3), (38, 3))

In [33]:
y_train[0]

array([0., 1., 0.], dtype=float32)

In [34]:
model = Sequential()
model.add(Dense(units=4, activation='relu', input_shape=(4,)))
model.add(Dense(units=3, activation='relu'))
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 9         
Total params: 52
Trainable params: 52
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

In [ ]:

model.fit(X_train, y_train, batch_size=1, epochs=50, verbose=1, validation_data=(X_valid, y_valid))

In [ ]:
model.evaluate(X_valid, y_valid)

2/2 [==============================] - 0s 8ms/step - loss: 0.1051 - accuracy: 0.6579


[0.10511653125286102, 0.6578947305679321]

In [ ]:
y_valid[0]

array([1., 0., 0.], dtype=float32)

In [ ]:
model.predict(X_valid[0].reshape(1,-1))

array([[0.7410781 , 0.1862702 , 0.07265177]], dtype=float32)

##Your Turn
- Build a Dense Network using continuous features to predict customer churn
- Experiment with different size layers and different activation functions
- Think about what activation makes sense for the output layer 

In [36]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving churn.csv to churn.csv
User uploaded file "churn.csv" with length 969287 bytes


In [37]:
import pandas as pd
churn_df = pd.read_csv('churn.csv')
churn_df.head()

State  Account Length  Area Code  ... Intl Charge CustServ Calls  Churn?
0    PA             163        806  ...    5.673203              3   True.
1    SC              15        836  ...    2.559749              8  False.
2    MO             131        777  ...    6.254157              4  False.
3    WY              75        878  ...    1.080692              6  False.
4    WY             146        878  ...    7.134343              6   True.

[5 rows x 21 columns]

In [38]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   State           5000 non-null   object 
 1   Account Length  5000 non-null   int64  
 2   Area Code       5000 non-null   int64  
 3   Phone           5000 non-null   object 
 4   Int'l Plan      5000 non-null   object 
 5   VMail Plan      5000 non-null   object 
 6   VMail Message   5000 non-null   int64  
 7   Day Mins        5000 non-null   float64
 8   Day Calls       5000 non-null   int64  
 9   Day Charge      5000 non-null   float64
 10  Eve Mins        5000 non-null   float64
 11  Eve Calls       5000 non-null   int64  
 12  Eve Charge      5000 non-null   float64
 13  Night Mins      5000 non-null   float64
 14  Night Calls     5000 non-null   int64  
 15  Night Charge    5000 non-null   float64
 16  Intl Mins       5000 non-null   float64
 17  Intl Calls      5000 non-null   i

In [39]:
import numpy as np

cols = ['Day Mins', 'Day Charge', 'Eve Mins', 'Eve Charge', 'Night Mins', 'Night Charge', 'Intl Mins', 'Intl Charge', 'CustServ Calls', 'Churn?']
churn_data = churn_df[cols].copy()
churn_data['Churn'] = np.where(churn_data['Churn?'] =='True.', 1, 0)
churn_data.head()

Day Mins  Day Charge  Eve Mins  ...  CustServ Calls  Churn?  Churn
0   8.162204    7.579174  3.933035  ...               3   True.      1
1  10.018993    4.226289  2.325005  ...               8  False.      0
2   4.708490    4.768160  4.537466  ...               4  False.      0
3   1.268734    2.567642  2.528748  ...               6  False.      0
4   2.696177    5.908916  6.015337  ...               6   True.      1

[5 rows x 11 columns]

In [40]:
churn_data['Churn'].value_counts()

0    2502
1    2498
Name: Churn, dtype: int64

In [41]:
features = ['Day Mins', 'Day Charge', 'Eve Mins', 'Eve Charge', 'Night Mins', 'Night Charge', 'Intl Mins', 'Intl Charge', 'CustServ Calls']
target = 'Churn'

X = churn_data[features].values
y = churn_data[target].values
X.shape, y.shape

((5000, 9), (5000,))

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=0)

X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((3750, 9), (1250, 9), (3750,), (1250,))

In [43]:
X_train

array([[13.23664371, 11.00768366,  5.54973717, ...,  6.12155121,
         3.12411923,  3.        ],
       [ 3.64623966,  4.11254353,  2.83378984, ...,  5.58227412,
         2.96599581,  7.        ],
       [ 0.53955568,  3.66313094,  0.08811627, ...,  4.46893939,
         1.29072559,  4.        ],
       ...,
       [10.40811761,  6.20244068,  7.00614012, ...,  4.32914583,
         4.21910436,  3.        ],
       [10.0109857 ,  7.35504399,  6.7736002 , ...,  3.69210465,
         6.18139625,  4.        ],
       [ 1.65060626,  4.23125228,  4.88634033, ...,  6.5126707 ,
         3.49669158,  5.        ]])

In [44]:
y_train

array([1, 0, 0, ..., 1, 1, 0])

Consider whether you should normalize using:
https://keras.io/api/utils/python_utils/#normalize-function

In [46]:
from tensorflow.keras.utils import normalize
normalize(X_train)

array([[0.58607787, 0.48738637, 0.24572529, ..., 0.27104346, 0.13832639,
        0.13283077],
       [0.26781313, 0.30206275, 0.2081394 , ..., 0.41001318, 0.21784981,
        0.51414392],
       [0.05635927, 0.3826322 , 0.00920418, ..., 0.4668029 , 0.13482269,
        0.41781985],
       ...,
       [0.55363115, 0.32992175, 0.37267233, ..., 0.23027699, 0.22442364,
        0.15957674],
       [0.51603819, 0.37913186, 0.34916006, ..., 0.19031762, 0.31863361,
        0.20618876],
       [0.13923357, 0.35691877, 0.41217741, ..., 0.54936323, 0.29495638,
        0.42176494]])

In [87]:
model = Sequential()
model.add(Dense(units=4, activation='relu', input_shape=(9,)))
model.add(Dense(units=7, activation='relu'))
model.add(Dense(units=5, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

In [88]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_52 (Dense)             (None, 4)                 40        
_________________________________________________________________
dense_53 (Dense)             (None, 7)                 35        
_________________________________________________________________
dense_54 (Dense)             (None, 5)                 40        
_________________________________________________________________
dense_55 (Dense)             (None, 1)                 6         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [89]:
model.compile(loss='mean_squared_error', optimizer=SGD(learning_rate=0.01), metrics=['accuracy'])

In [90]:
model.fit(X_train, y_train, batch_size=1, epochs=30, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/30
3750/3750 [==============================] - 5s 1ms/step - loss: 0.1859 - accuracy: 0.7330 - val_loss: 0.1503 - val_accuracy: 0.7880
Epoch 2/30
3750/3750 [==============================] - 4s 1ms/step - loss: 0.1505 - accuracy: 0.7857 - val_loss: 0.1508 - val_accuracy: 0.7904
Epoch 3/30
3750/3750 [==============================] - 4s 1ms/step - loss: 0.1481 - accuracy: 0.7966 - val_loss: 0.1646 - val_accuracy: 0.7680
Epoch 4/30
3750/3750 [==============================] - 4s 1ms/step - loss: 0.1451 - accuracy: 0.8025 - val_loss: 0.1468 - val_accuracy: 0.7992
Epoch 5/30
3750/3750 [==============================] - 4s 1ms/step - loss: 0.1416 - accuracy: 0.7972 - val_loss: 0.1485 - val_accuracy: 0.7960
Epoch 6/30
3750/3750 [==============================] - 4s 1ms/step - loss: 0.1421 - accuracy: 0.7933 - val_loss: 0.1464 - val_accuracy: 0.7832
Epoch 7/30
3750/3750 [==============================] - 4s 1ms/step - loss: 0.1375 - accuracy: 0.8037 - val_loss: 0.1458 - val_accuracy:

In [91]:
model.evaluate(X_valid, y_valid)

40/40 [==============================] - 0s 2ms/step - loss: 0.0898 - accuracy: 0.8792


[0.08977027237415314, 0.8791999816894531]

In [92]:
y_valid[0]

0

In [93]:
model.predict(X_valid[0].reshape(1,-1))

array([[3.5282855e-07]], dtype=float32)